version: '3.8'

services:
  graphql-app:
    build: ./
    command: ./wait-for-postgres.sh db ./graphql-app
    ports:
      - 8989:8989
    depends_on:
      - db
    environment:
      - DB_PASSWORD=qwerty

  db:
    restart: always
    image: postgres:latest
    volumes:
    - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432