// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewReminder struct {
	Text   string `json:"text"`
	TodoID int    `json:"todoId"`
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
}

type Reminder struct {
	ID   int    `json:"id"`
	Text string `json:"text"`
	Todo *Todo  `json:"todo"`
}

type Todo struct {
	ID   int    `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID         int    `json:"id"`
	Name       string `json:"name"`
	CreditCard string `json:"creditCard"`
}
